#include <Rendering/Base/Resource/DataFormat.h>

const GLenum Miracle::DataFormatUtils::OpenGLDataFormat[] =
{
	GL_ZERO,                        
	GL_BYTE,                        
	GL_UNSIGNED_BYTE,               
	GL_SHORT,                       
	GL_UNSIGNED_SHORT,              
	GL_INT,                         
	GL_UNSIGNED_INT,                
	GL_HALF_FLOAT,                  
	GL_FLOAT,                       
	GL_DOUBLE,                      
	GL_INT_2_10_10_10_REV,          
	GL_UNSIGNED_INT_2_10_10_10_REV, 
	GL_UNSIGNED_INT_10F_11F_11F_REV 
};

const _U32 Miracle::DataFormatUtils::NumBytesPerStruct[Miracle::DataFormat::NUM_DIRECTX_FORMATS] =
{
	0,   // MENGINE_UNKNOWN
	16,  // MENGINE_R32G32B32A32_TYPELESS
	16,  // MENGINE_R32G32B32A32_FLOAT
	16,  // MENGINE_R32G32B32A32_UINT
	16,  // MENGINE_R32G32B32A32_SINT
	12,  // MENGINE_R32G32B32_TYPELESS
	12,  // MENGINE_R32G32B32_FLOAT
	12,  // MENGINE_R32G32B32_UINT
	12,  // MENGINE_R32G32B32_SINT
	8,   // MENGINE_R16G16B16A16_TYPELESS
	8,   // MENGINE_R16G16B16A16_FLOAT
	8,   // MENGINE_R16G16B16A16_UNORM
	8,   // MENGINE_R16G16B16A16_UINT
	8,   // MENGINE_R16G16B16A16_SNORM
	8,   // MENGINE_R16G16B16A16_SINT
	8,   // MENGINE_R32G32_TYPELESS
	8,   // MENGINE_R32G32_FLOAT
	8,   // MENGINE_R32G32_UINT
	8,   // MENGINE_R32G32_SINT
	8,   // MENGINE_R32G8X24_TYPELESS
	4,   // MENGINE_D32_FLOAT_S8X24_UINT
	4,   // MENGINE_R32_FLOAT_X8X24_TYPELESS
	4,   // MENGINE_X32_TYPELESS_G8X24_UINT
	4,   // MENGINE_R10G10B10A2_TYPELESS
	4,   // MENGINE_R10G10B10A2_UNORM
	4,   // MENGINE_R10G10B10A2_UINT
	4,   // MENGINE_R11G11B10_FLOAT
	4,   // MENGINE_R8G8B8A8_TYPELESS
	4,   // MENGINE_R8G8B8A8_UNORM
	4,   // MENGINE_R8G8B8A8_UNORM_SRGB
	4,   // MENGINE_R8G8B8A8_UINT
	4,   // MENGINE_R8G8B8A8_SNORM
	4,   // MENGINE_R8G8B8A8_SINT
	4,   // MENGINE_R16G16_TYPELESS
	4,   // MENGINE_R16G16_FLOAT
	4,   // MENGINE_R16G16_UNORM
	4,   // MENGINE_R16G16_UINT
	4,   // MENGINE_R16G16_SNORM
	4,   // MENGINE_R16G16_SINT
	4,   // MENGINE_R32_TYPELESS
	4,   // MENGINE_D32_FLOAT
	4,   // MENGINE_R32_FLOAT
	4,   // MENGINE_R32_UINT
	4,   // MENGINE_R32_SINT
	4,   // MENGINE_R24G8_TYPELESS
	4,   // MENGINE_D24_UNORM_S8_UINT
	4,   // MENGINE_R24_UNORM_X8_TYPELESS
	4,   // MENGINE_X24_TYPELESS_G8_UINT
	2,   // MENGINE_R8G8_TYPELESS
	2,   // MENGINE_R8G8_UNORM
	2,   // MENGINE_R8G8_UINT
	2,   // MENGINE_R8G8_SNORM
	2,   // MENGINE_R8G8_SINT
	2,   // MENGINE_R16_TYPELESS
	2,   // MENGINE_R16_FLOAT
	2,   // MENGINE_D16_UNORM
	2,   // MENGINE_R16_UNORM
	2,   // MENGINE_R16_UINT
	2,   // MENGINE_R16_SNORM
	2,   // MENGINE_R16_SINT
	1,   // MENGINE_R8_TYPELESS
	1,   // MENGINE_R8_UNORM
	1,   // MENGINE_R8_UINT
	1,   // MENGINE_R8_SNORM
	1,   // MENGINE_R8_SINT
	1,   // MENGINE_A8_UNORM
	0,   // MENGINE_R1_UNORM
	2,   // MENGINE_R9G9B9E5_SHAREDEXP
	2,   // MENGINE_R8G8_B8G8_UNORM
	2,   // MENGINE_G8R8_G8B8_UNORM
	0,   // MENGINE_BC1_TYPELESS
	0,   // MENGINE_BC1_UNORM
	0,   // MENGINE_BC1_UNORM_SRGB
	0,   // MENGINE_BC2_TYPELESS
	0,   // MENGINE_BC2_UNORM
	0,   // MENGINE_BC2_UNORM_SRGB
	0,   // MENGINE_BC3_TYPELESS
	0,   // MENGINE_BC3_UNORM
	0,   // MENGINE_BC3_UNORM_SRGB
	0,   // MENGINE_BC4_TYPELESS
	0,   // MENGINE_BC4_UNORM
	0,   // MENGINE_BC4_SNORM
	0,   // MENGINE_BC5_TYPELESS
	0,   // MENGINE_BC5_UNORM
	0,   // MENGINE_BC5_SNORM
	2,   // MENGINE_B5G6R5_UNORM
	2,   // MENGINE_B5G5R5A1_UNORM
	4,   // MENGINE_B8G8R8A8_UNORM
	4,   // MENGINE_B8G8R8X8_UNORM
	4,   // MENGINE_R10G10B10_XR_BIAS_A2_UNORM
	4,   // MENGINE_B8G8R8A8_TYPELESS
	4,   // MENGINE_B8G8R8A8_UNORM_SRGB
	4,   // MENGINE_B8G8R8X8_TYPELESS
	4,   // MENGINE_B8G8R8X8_UNORM_SRGB
	0,   // MENGINE_BC6H_TYPELESS
	0,   // MENGINE_BC6H_UF16
	0,   // MENGINE_BC6H_SF16
	0,   // MENGINE_BC7_TYPELESS
	0,   // MENGINE_BC7_UNORM
	0,   // MENGINE_BC7_UNORM_SRGB
	0,   // MENGINE_AYUV
	0,   // MENGINE_Y410
	0,   // MENGINE_Y416
	0,   // MENGINE_NV12
	0,   // MENGINE_P010
	0,   // MENGINE_P016
	0,   // MENGINE_420_OPAQUE
	0,   // MENGINE_YUY2
	0,   // MENGINE_Y210
	0,   // MENGINE_Y216
	0,   // MENGINE_NV11
	0,   // MENGINE_AI44
	0,   // MENGINE_IA44
	0,   // MENGINE_P8
	0,   // MENGINE_A8P8
	0    // MENGINE_B4G4R4A4_UNORM
};

const _U32 Miracle::DataFormatUtils::NumChannles[Miracle::DataFormat::NUM_DIRECTX_FORMATS] =
{
	0,  // MENGINE_UNKNOWN
	4,  // MENGINE_R32G32B32A32_TYPELESS
	4,  // MENGINE_R32G32B32A32_FLOAT
	4,  // MENGINE_R32G32B32A32_UINT
	4,  // MENGINE_R32G32B32A32_SINT
	3,  // MENGINE_R32G32B32_TYPELESS
	3,  // MENGINE_R32G32B32_FLOAT
	3,  // MENGINE_R32G32B32_UINT
	3,  // MENGINE_R32G32B32_SINT
	4,  // MENGINE_R16G16B16A16_TYPELESS
	4,  // MENGINE_R16G16B16A16_FLOAT
	4,  // MENGINE_R16G16B16A16_UNORM
	4,  // MENGINE_R16G16B16A16_UINT
	4,  // MENGINE_R16G16B16A16_SNORM
	4,  // MENGINE_R16G16B16A16_SINT
	2,  // MENGINE_R32G32_TYPELESS
	2,  // MENGINE_R32G32_FLOAT
	2,  // MENGINE_R32G32_UINT
	2,  // MENGINE_R32G32_SINT
	2,  // MENGINE_R32G8X24_TYPELESS
	2,  // MENGINE_D32_FLOAT_S8X24_UINT
	2,  // MENGINE_R32_FLOAT_X8X24_TYPELESS
	2,  // MENGINE_X32_TYPELESS_G8X24_UINT
	4,  // MENGINE_R10G10B10A2_TYPELESS
	4,  // MENGINE_R10G10B10A2_UNORM
	4,  // MENGINE_R10G10B10A2_UINT
	3,  // MENGINE_R11G11B10_FLOAT
	4,  // MENGINE_R8G8B8A8_TYPELESS
	4,  // MENGINE_R8G8B8A8_UNORM
	4,  // MENGINE_R8G8B8A8_UNORM_SRGB
	4,  // MENGINE_R8G8B8A8_UINT
	4,  // MENGINE_R8G8B8A8_SNORM
	4,  // MENGINE_R8G8B8A8_SINT
	2,  // MENGINE_R16G16_TYPELESS
	2,  // MENGINE_R16G16_FLOAT
	2,  // MENGINE_R16G16_UNORM
	2,  // MENGINE_R16G16_UINT
	2,  // MENGINE_R16G16_SNORM
	2,  // MENGINE_R16G16_SINT
	1,  // MENGINE_R32_TYPELESS
	1,  // MENGINE_D32_FLOAT
	1,  // MENGINE_R32_FLOAT
	1,  // MENGINE_R32_UINT
	1,  // MENGINE_R32_SINT
	2,  // MENGINE_R24G8_TYPELESS
	2,  // MENGINE_D24_UNORM_S8_UINT
	2,  // MENGINE_R24_UNORM_X8_TYPELESS
	2,  // MENGINE_X24_TYPELESS_G8_UINT
	2,  // MENGINE_R8G8_TYPELESS
	2,  // MENGINE_R8G8_UNORM
	2,  // MENGINE_R8G8_UINT
	2,  // MENGINE_R8G8_SNORM
	2,  // MENGINE_R8G8_SINT
	1,  // MENGINE_R16_TYPELESS
	1,  // MENGINE_R16_FLOAT
	1,  // MENGINE_D16_UNORM
	1,  // MENGINE_R16_UNORM
	1,  // MENGINE_R16_UINT
	1,  // MENGINE_R16_SNORM
	1,  // MENGINE_R16_SINT
	1,  // MENGINE_R8_TYPELESS
	1,  // MENGINE_R8_UNORM
	1,  // MENGINE_R8_UINT
	1,  // MENGINE_R8_SNORM
	1,  // MENGINE_R8_SINT
	1,  // MENGINE_A8_UNORM
	1,  // MENGINE_R1_UNORM
	4,  // MENGINE_R9G9B9E5_SHAREDEXP
	4,  // MENGINE_R8G8_B8G8_UNORM
	4,  // MENGINE_G8R8_G8B8_UNORM
	0,  // MENGINE_BC1_TYPELESS
	0,  // MENGINE_BC1_UNORM
	0,  // MENGINE_BC1_UNORM_SRGB
	0,  // MENGINE_BC2_TYPELESS
	0,  // MENGINE_BC2_UNORM
	0,  // MENGINE_BC2_UNORM_SRGB
	0,  // MENGINE_BC3_TYPELESS
	0,  // MENGINE_BC3_UNORM
	0,  // MENGINE_BC3_UNORM_SRGB
	0,  // MENGINE_BC4_TYPELESS
	0,  // MENGINE_BC4_UNORM
	0,  // MENGINE_BC4_SNORM
	0,  // MENGINE_BC5_TYPELESS
	0,  // MENGINE_BC5_UNORM
	0,  // MENGINE_BC5_SNORM
	2,  // MENGINE_B5G6R5_UNORM
	4,  // MENGINE_B5G5R5A1_UNORM
	4,  // MENGINE_B8G8R8A8_UNORM
	4,  // MENGINE_B8G8R8X8_UNORM
	4,  // MENGINE_R10G10B10_XR_BIAS_A2_UNORM
	4,  // MENGINE_B8G8R8A8_TYPELESS
	4,  // MENGINE_B8G8R8A8_UNORM_SRGB
	4,  // MENGINE_B8G8R8X8_TYPELESS
	4,  // MENGINE_B8G8R8X8_UNORM_SRGB
	0,  // MENGINE_BC6H_TYPELESS
	0,  // MENGINE_BC6H_UF16
	0,  // MENGINE_BC6H_SF16
	0,  // MENGINE_BC7_TYPELESS
	0,  // MENGINE_BC7_UNORM
	0,  // MENGINE_BC7_UNORM_SRGB
	0,  // MENGINE_AYUV
	0,  // MENGINE_Y410
	0,  // MENGINE_Y416
	0,  // MENGINE_NV12
	0,  // MENGINE_P010
	0,  // MENGINE_P016
	0,  // MENGINE_420_OPAQUE
	0,  // MENGINE_YUY2
	0,  // MENGINE_Y210
	0,  // MENGINE_Y216
	0,  // MENGINE_NV11
	0,  // MENGINE_AI44
	0,  // MENGINE_IA44
	0,  // MENGINE_P8
	0,  // MENGINE_A8P8
	0   // MENGINE_B4G4R4A4_UNORM
};

const _U32 Miracle::DataFormatUtils::ChannelType[Miracle::DataFormat::NUM_DIRECTX_FORMATS] =
{
	MENGINE_UNSUPPORTED,     	   // MENGINE_UNKNOWN
	MENGINE_UNSUPPORTED,   		   // MENGINE_R32G32B32A32_TYPELESS
	MENGINE_FLOAT,         		   // MENGINE_R32G32B32A32_FLOAT
	MENGINE_UINT,          		   // MENGINE_R32G32B32A32_UINT
	MENGINE_INT,           		   // MENGINE_R32G32B32A32_SINT
	MENGINE_UNSUPPORTED,   		   // MENGINE_R32G32B32_TYPELESS
	MENGINE_FLOAT,         		   // MENGINE_R32G32B32_FLOAT
	MENGINE_UINT,          		   // MENGINE_R32G32B32_UINT
	MENGINE_INT,           		   // MENGINE_R32G32B32_SINT
	MENGINE_UNSUPPORTED,   		   // MENGINE_R16G16B16A16_TYPELESS
	MENGINE_HALF_FLOAT,    		   // MENGINE_R16G16B16A16_FLOAT
	MENGINE_USHORT,        		   // MENGINE_R16G16B16A16_UNORM
	MENGINE_USHORT,        		   // MENGINE_R16G16B16A16_UINT
	MENGINE_SHORT,         		   // MENGINE_R16G16B16A16_SNORM
	MENGINE_SHORT,         		   // MENGINE_R16G16B16A16_SINT
	MENGINE_UNSUPPORTED,   		   // MENGINE_R32G32_TYPELESS
	MENGINE_FLOAT,           	   // MENGINE_R32G32_FLOAT
	MENGINE_UINT,            	   // MENGINE_R32G32_UINT
	MENGINE_INT,             	   // MENGINE_R32G32_SINT
	MENGINE_UNSUPPORTED,    	   // MENGINE_R32G8X24_TYPELESS
	MENGINE_UNSUPPORTED,    	   // MENGINE_D32_FLOAT_S8X24_UINT
	MENGINE_UNSUPPORTED,    	   // MENGINE_R32_FLOAT_X8X24_TYPELESS
	MENGINE_UNSUPPORTED,    	   // MENGINE_X32_TYPELESS_G8X24_UINT
	MENGINE_UNSUPPORTED,    	   // MENGINE_R10G10B10A2_TYPELESS
	MENGINE_UINT_10_10_2,   	   // MENGINE_R10G10B10A2_UNORM
	MENGINE_UINT_10_10_2,   	   // MENGINE_R10G10B10A2_UINT
	MENGINE_FLOAT_11_11_10, 	   // MENGINE_R11G11B10_FLOAT
	MENGINE_UNSUPPORTED,    	   // MENGINE_R8G8B8A8_TYPELESS
	MENGINE_UBYTE,          	   // MENGINE_R8G8B8A8_UNORM
	MENGINE_UBYTE,          	   // MENGINE_R8G8B8A8_UNORM_SRGB
	MENGINE_UBYTE,          	   // MENGINE_R8G8B8A8_UINT
	MENGINE_BYTE,            	   // MENGINE_R8G8B8A8_SNORM
	MENGINE_BYTE,            	   // MENGINE_R8G8B8A8_SINT
	MENGINE_UNSUPPORTED,     	   // MENGINE_R16G16_TYPELESS
	MENGINE_FLOAT,           	   // MENGINE_R16G16_FLOAT
	MENGINE_USHORT,          	   // MENGINE_R16G16_UNORM
	MENGINE_USHORT,          	   // MENGINE_R16G16_UINT
	MENGINE_SHORT,           	   // MENGINE_R16G16_SNORM
	MENGINE_SHORT,           	   // MENGINE_R16G16_SINT
	MENGINE_UNSUPPORTED,     	   // MENGINE_R32_TYPELESS
	MENGINE_FLOAT,           	   // MENGINE_D32_FLOAT
	MENGINE_FLOAT,           	   // MENGINE_R32_FLOAT
	MENGINE_UINT,            	   // MENGINE_R32_UINT
	MENGINE_INT,             	   // MENGINE_R32_SINT
	MENGINE_UNSUPPORTED,     	   // MENGINE_R24G8_TYPELESS
	MENGINE_UINT,            	   // MENGINE_D24_UNORM_S8_UINT
	MENGINE_UNSUPPORTED,     	   // MENGINE_R24_UNORM_X8_TYPELESS
	MENGINE_UNSUPPORTED,     	   // MENGINE_X24_TYPELESS_G8_UINT
	MENGINE_UNSUPPORTED,     	   // MENGINE_R8G8_TYPELESS
	MENGINE_UBYTE,           	   // MENGINE_R8G8_UNORM
	MENGINE_UBYTE,           	   // MENGINE_R8G8_UINT
	MENGINE_BYTE,            	   // MENGINE_R8G8_SNORM
	MENGINE_BYTE,            	   // MENGINE_R8G8_SINT
	MENGINE_UNSUPPORTED,     	   // MENGINE_R16_TYPELESS
	MENGINE_HALF_FLOAT,      	   // MENGINE_R16_FLOAT
	MENGINE_USHORT,          	   // MENGINE_D16_UNORM
	MENGINE_USHORT,          	   // MENGINE_R16_UNORM
	MENGINE_USHORT,          	   // MENGINE_R16_UINT
	MENGINE_SHORT,           	   // MENGINE_R16_SNORM
	MENGINE_SHORT,           	   // MENGINE_R16_SINT
	MENGINE_UNSUPPORTED,     	   // MENGINE_R8_TYPELESS
	MENGINE_UBYTE,           	   // MENGINE_R8_UNORM
	MENGINE_UBYTE,           	   // MENGINE_R8_UINT
	MENGINE_BYTE,            	   // MENGINE_R8_SNORM
	MENGINE_BYTE,            	   // MENGINE_R8_SINT
	MENGINE_UNSUPPORTED,     	   // MENGINE_A8_UNORM
	MENGINE_UNSUPPORTED,     	   // MENGINE_R1_UNORM
	MENGINE_UNSUPPORTED,     	   // MENGINE_R9G9B9E5_SHAREDEXP
	MENGINE_UNSUPPORTED,     	   // MENGINE_R8G8_B8G8_UNORM
	MENGINE_UNSUPPORTED,     	   // MENGINE_G8R8_G8B8_UNORM
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC1_TYPELESS
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC1_UNORM
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC1_UNORM_SRGB
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC2_TYPELESS
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC2_UNORM
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC2_UNORM_SRGB
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC3_TYPELESS
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC3_UNORM
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC3_UNORM_SRGB
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC4_TYPELESS
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC4_UNORM
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC4_SNORM
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC5_TYPELESS
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC5_UNORM
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC5_SNORM
	MENGINE_UNSUPPORTED,     	   // MENGINE_B5G6R5_UNORM
	MENGINE_UNSUPPORTED,     	   // MENGINE_B5G5R5A1_UNORM
	MENGINE_UNSUPPORTED,     	   // MENGINE_B8G8R8A8_UNORM
	MENGINE_UNSUPPORTED,     	   // MENGINE_B8G8R8X8_UNORM
	MENGINE_UNSUPPORTED,    	   // MENGINE_R10G10B10_XR_BIAS_A2_UNORM
	MENGINE_UNSUPPORTED,    	   // MENGINE_B8G8R8A8_TYPELESS
	MENGINE_UNSUPPORTED,    	   // MENGINE_B8G8R8A8_UNORM_SRGB
	MENGINE_UNSUPPORTED,    	   // MENGINE_B8G8R8X8_TYPELESS
	MENGINE_UNSUPPORTED,    	   // MENGINE_B8G8R8X8_UNORM_SRGB
	MENGINE_UNSUPPORTED,    	   // MENGINE_BC6H_TYPELESS
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC6H_UF16
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC6H_SF16
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC7_TYPELESS
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC7_UNORM
	MENGINE_UNSUPPORTED,     	   // MENGINE_BC7_UNORM_SRGB
	MENGINE_UNSUPPORTED,     	   // MENGINE_AYUV
	MENGINE_UNSUPPORTED,     	   // MENGINE_Y410
	MENGINE_UNSUPPORTED,     	   // MENGINE_Y416
	MENGINE_UNSUPPORTED,     	   // MENGINE_NV12
	MENGINE_UNSUPPORTED,     	   // MENGINE_P010
	MENGINE_UNSUPPORTED,     	   // MENGINE_P016
	MENGINE_UNSUPPORTED,     	   // MENGINE_420_OPAQUE
	MENGINE_UNSUPPORTED,     	   // MENGINE_YUY2
	MENGINE_UNSUPPORTED,     	   // MENGINE_Y210
	MENGINE_UNSUPPORTED,     	   // MENGINE_Y216
	MENGINE_UNSUPPORTED,     	   // MENGINE_NV11
	MENGINE_UNSUPPORTED,     	   // MENGINE_AI44
	MENGINE_UNSUPPORTED,     	   // MENGINE_IA44
	MENGINE_UNSUPPORTED,     	   // MENGINE_P8
	MENGINE_UNSUPPORTED,     	   // MENGINE_A8P8
	MENGINE_UNSUPPORTED      	   // MENGINE_B4G4R4A4_UNORM
};

_U32 Miracle::DataFormatUtils::GetChannels(DataFormat a_Format)
{
	return ChannelType[a_Format];
}

GLenum Miracle::DataFormatUtils::GetOpenGLChannelType(DataFormat a_Format)
{
	return OpenGLDataFormat[GetChannels(a_Format)];
}

_U32 Miracle::DataFormatUtils::GetDataFormatBytes(DataFormat a_Format)
{
	return NumBytesPerStruct[a_Format];
}

_U32 Miracle::DataFormatUtils::GetDataFormatChannles(DataFormat a_Format)
{
	return NumChannles[a_Format];
}

bool Miracle::DataFormatUtils::IsDepth(DataFormat a_Format)
{
	return a_Format == MENGINE_D32_FLOAT_S8X24_UINT
		|| a_Format == MENGINE_D32_FLOAT
		|| a_Format == MENGINE_D24_UNORM_S8_UINT
		|| a_Format == MENGINE_D16_UNORM;
}
